services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/html/public
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
