version: '3.8'

services:
  laravel_nginx:
    image: nginx:latest
    networks:
      - laravel_network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
      - ./src:/var/www/html  
    depends_on:
      - laravel_backend
      - mysql_db

  laravel_backend:
    image: bemysample_backend-backend 
    networks:
      - laravel_network
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=somekeyhere
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_db  
      - DB_PORT=3306
      - DB_DATABASE=bms  
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword 
    volumes:
      - ./src:/var/www/html  

  mysql_db:
    image: mysql:8.0  
    networks:
      - laravel_network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set a root password
      MYSQL_DATABASE: bms  
    ports:
      - "3306:3306"  # port mysqk
    volumes:
      - mysql_data:/var/lib/mysql  

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
